repos:
  - hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-builtin-literals
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: detect-aws-credentials
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--no-ensure-ascii"
      - id: mixed-line-ending
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
  - hooks:
      - id: commitizen
        stages:
          - commit-msg
        additional_dependencies:
          - cz-github-jira-conventional~=3.0
    repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
  - hooks:
      - id: python-check-blanket-type-ignore
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
    repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
  - hooks:
      - id: pycln
    repo: https://github.com/hadialqattan/pycln
    rev: v2.5.0
  - hooks:
      - id: isort
    repo: https://github.com/pycqa/isort
    rev: 6.0.1
  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 25.1.0
  - hooks:
      - additional_dependencies:
          - flake8-absolute-import~=1.0
          - flake8-bandit~=4.1
          - flake8-bugbear~=24.12
          - flake8-builtins~=2.5
          - flake8-comprehensions~=3.16
          - flake8-isort~=6.1
          - flake8-print~=5.0
          - flake8-pyproject~=1.2
          - flake8-return~=1.2
          - flake8-use-pathlib~=0.3
          - pep8-naming~=0.14
          - setuptools~=76.1.0
        id: flake8
    repo: https://github.com/pycqa/flake8
    rev: 7.1.2
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.15.0"
    hooks:
      - id: mypy
        additional_dependencies:
          - boto3-stubs[boto3,dynamodb,s3]~=1.36
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
      - id: taplo-lint
