version: 0.1
default:
  global:
    parameters:
      region: us-east-1
      s3_bucket: arine-packages-dev-us-east-1
      s3_prefix: arine-api
  build:
    parameters:
      template_file: ./stack.yaml
  sync:
    parameters:
      template_file: ./stack.yaml
  deploy:
    parameters:
      template_file: .aws-sam/build/template.yaml
      parameter_overrides: []
      capabilities: CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
