AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: PDF Optimization, Validation, and Transmogrification (OVT) Service

Globals:
  Function:
    Timeout: 5
    Runtime: python3.13
    Tracing: Active
    Environment:
      Variables:
        POWERTOOLS_LOG_LEVEL: INFO
        # POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
        POWERTOOLS_LOGGER_LOG_EVENT: true
        POWERTOOLS_SERVICE_NAME:
          Fn::Sub: ${AWS::StackName}_pdf-ovt-service

Resources:
  ArinePdfOvtProgramsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${AWS::StackName}_pdf-ovt-programs-layer
      Description: Arine PDF Optimization, Validation, and Transmogrification (OVT) Programs Layer
      ContentUri: ./build/programs.zip
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete

  ArinePdfOvtRequirementsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${AWS::StackName}_pdf-ovt-requirements-layer
      Description: Arine PDF Optimization, Validation, and Transmogrification (OVT) Requirements Layer
      ContentUri: ./build/requirements.zip
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete

  ArinePdfOvtLayerHealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}_pdf-ovt-layer-health-check
      Description: Health check for the Arine PDF Optimization, Validation, and Transmogrification (OVT) Service
      CodeUri: ./src
      Handler: pdf_optimization_validation_and_transmogrification_service.handlers.health_check.lambda_handler
      Architectures:
        - arm64
      Layers:
        - Ref: ArinePdfOvtProgramsLayer
        - Ref: ArinePdfOvtRequirementsLayer
