on:
  workflow_dispatch:

jobs:
  build-layer:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:layer"
          load: false
          push: false
          outputs: type=local,dest=python
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Print size of asset
        run: |
          du -sh layer/python
