on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-layer:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: layers/programs/Dockerfile
          load: false
          push: false
          outputs: type=local,dest=programs
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: layers/requirements/Dockerfile
          load: false
          push: false
          outputs: type=local,dest=requirements
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Report sizes
        run: |
          echo "Programs layer size:"
          du -sh programs
          echo "Requirements layer size:"
          du -sh requirements

      # # If this is a release upload the layer asset to the release.
      # - name: Upload layer asset
      #   if: github.event_name == 'release' && github.event.action == 'published'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: layer-asset
      #     path: python
